# Dockerfile-node
FROM node:21

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY node/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY node/ .

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["node", "index.js"]

