# Dockerfile-python
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy requirements.txt
COPY python/requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY python/ .

# Expose port (assuming the FastAPI app runs on port 8000)
EXPOSE 8000

# Command to run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
